import { config } from 'dotenv'

config({ path: '.env' })

export const {
  PORT,
  SMTP_EMAIL,
  SMTP_PASSWORD,
  LOG_DIR,
  SECRET_KEY,
  FRONTEND_URL,
  CSRF_ENABLED,
  NODE_ENV,
  REFRESH_TOKEN_SECRET_KEY,
  SESSION_TOKEN_SECRET,
  SESSION_TOKEN_EXPIRES,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_EXPIRES_SECONDS,
  COOKIE_DOMAIN,
  BASE_URL
} = process.env
